=== MrBartusek/MeteoalarmCard/src/localize/schema/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object",
    "required": [
        "$schema",
        "common",
        "error",
        "editor",
        "events",
        "messages"
    ],
    "properties": {
         "$schema": {
              "$id": "#/properties/%24schema",
              "type": "string"
         },
        "common": {
            "$id": "#/properties/common",
            "type": "object",
            "required": [
                "name",
                "description",
                "expected",
                "unavailable"
            ],
            "properties": {
                "name": {
                    "$id": "#/properties/common/properties/name",
                    "type": ["string", "null"]
                },
                "description": {
                    "$id": "#/properties/common/properties/description",
                    "type": ["string", "null"]
                },
                "expected": {
                    "$id": "#/properties/common/properties/expected",
                    "type": ["string", "null"]
                },
                "unavailable": {
                    "$id": "#/properties/common/properties/unavailable",
                    "type": "object",
                    "required": [
                        "long",
                        "short"
                    ],
                    "properties": {
                        "long": {
                            "$id": "#/properties/common/properties/unavailable/properties/long",
                            "type": ["string", "null"]
                        },
                        "short": {
                            "$id": "#/properties/common/properties/unavailable/properties/short",
                            "type": ["string", "null"]
                        }
                    },
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        },
        "error": {
            "$id": "#/properties/error",
            "type": "object",
            "required": [
                "missing_entity",
                "invalid_integration",
                "invalid_scaling_mode",
                "entity_invalid"
            ],
            "properties": {
                "missing_entity": {
                    "$id": "#/properties/error/properties/missing_entity",
                    "type": ["string", "null"]
                },
                "invalid_integration": {
                    "$id": "#/properties/error/properties/invalid_integration",
                    "type": ["string", "null"]
                },
                "invalid_scaling_mode": {
                    "$id": "#/properties/error/properties/invalid_scaling_mode",
                    "type": ["string", "null"]
                },
                "entity_invalid": {
                    "$id": "#/properties/error/properties/entity_invalid",
                    "type": "object",
                    "required": [
                        "single",
                        "multiple"
                    ],
                    "properties": { 
                        "single": {
                            "$id": "#/properties/error/properties/entity_invalid/properties/single",
                            "type": ["string", "null"]
                        },
                        "multiple": {
                            "$id": "#/properties/error/properties/entity_invalid/properties/multiple",
                            "type": ["string", "null"]
                        }
                    },
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        },
        "editor": {
            "$id": "#/properties/editor",
            "type": "object",
            "required": [
                "entity",
                "entities",
                "integration",
                "required",
                "recommended",
                "override_headline",
                "hide_when_no_warning",
                "hide_caption",
                "disable_swiper",
                "description",
                "error",
                "scaling_mode",
                "scaling_mode_options"
            ],
            "properties": {
                "entity": {
                    "$id": "#/properties/editor/properties/entity",
                    "type": ["string", "null"]
                },
                "entities": {
                    "$id": "#/properties/editor/properties/entities",
                    "type": ["string", "null"]
                },
                "integration": {
                    "$id": "#/properties/editor/properties/integration",
                    "type": ["string", "null"]
                },
                "required": {
                    "$id": "#/properties/editor/properties/required",
                    "type": ["string", "null"]
                },
                "recommended": {
                    "$id": "#/properties/editor/properties/recommended",
                    "type": ["string", "null"]
                },
                "override_headline": {
                  "$id": "#/properties/editor/properties/override_headline",
                  "type": ["string", "null"]
                },
                "hide_when_no_warning": {
                    "$id": "#/properties/editor/properties/hide_when_no_warning",
                    "type": ["string", "null"]
                },
                "hide_caption": {
                    "$id": "#/properties/editor/properties/hide_caption",
                    "type": ["string", "null"]
                },
                "disable_swiper": {
                    "$id": "#/properties/editor/properties/disable_swiper",
                    "type": ["string", "null"]
                },
                "description": {
                    "$id": "#/properties/editor/properties/description",
                    "type": "object",
                    "required": [
                        "start",
                        "current_expected",
                        "slots",
                        "separate_events",
                        "warning_watch_statement_advisory",
                        "end"
                    ],
                    "properties": { 
                        "start": {
                            "$id": "#/properties/editor/properties/description/properties/start",
                            "type": ["string", "null"]
                        },
                        "current_expected": {
                            "$id": "#/properties/editor/properties/description/properties/current_expected",
                            "type": ["string", "null"]
                        },
                        "slots": {
                            "$id": "#/properties/editor/properties/description/properties/slots",
                            "type": ["string", "null"]
                        },
                        "separate_events": {
                            "$id": "#/properties/editor/properties/description/properties/separate_events",
                            "type": ["string", "null"]
                        },
                        "warning_watch_statement_advisory": {
                            "$id": "#/properties/editor/properties/description/properties/warning_watch_statement_advisory",
                            "type": ["string", "null"]
                        },
                        "end": {
                            "$id": "#/properties/editor/properties/description/properties/end",
                            "type": ["string", "null"]
                        }
                    },
                    "additionalProperties": false
                },
                "error": {
                    "$id": "#/properties/editor/properties/error",
                    "type": "object",
                    "required": [
                        "expected_entity",
                        "too_many_entities",
                        "duplicate"
                    ],
                    "properties": { 
                        "expected_entity": {
                            "$id": "#/properties/editor/properties/error/properties/expected_entity",
                            "type": ["string", "null"]
                        },
                        "too_many_entities": {
                            "$id": "#/properties/editor/properties/error/properties/too_many_entities",
                            "type": ["string", "null"]
                        },
                        "duplicate": {
                            "$id": "#/properties/editor/properties/error/properties/duplicate",
                            "type": ["string", "null"]
                        }
                    },
                    "additionalProperties": false
                },
                "scaling_mode": {
                    "$id": "#/properties/editor/properties/scaling_mode",
                    "type": ["string", "null"]
                },
                "scaling_mode_options": {
                    "$id": "#/properties/editor/properties/scaling_mode_options",
                    "type": "object",
                    "required": [
                        "disabled",
                        "headline",
                        "scale",
                        "headline_and_scale"
                    ],
                    "properties": {
                        "disabled": {
                            "$id": "#/properties/editor/properties/scaling_mode_options/properties/disabled",
                            "type": ["string", "null"]
                        },
                        "headline": {
                            "$id": "#/properties/editor/properties/scaling_mode_options/properties/headline",
                            "type": ["string", "null"]
                        },
                        "scale": {
                            "$id": "#/properties/editor/properties/scaling_mode_options/properties/scale",
                            "type": ["string", "null"]
                        },
                        "headline_and_scale": {
                            "$id": "#/properties/editor/properties/scaling_mode_options/properties/headline_and_scale",
                            "type": ["string", "null"]
                        }
                    },
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        },
        "events": {
            "$id": "#/properties/events",
            "type": "object",
            "required": [
                "no_warnings",
                "nuclear",
                "hurricane",
                "wind",
                "snow_ice",
                "thunderstorms",
                "fog",
                "high_temperature",
                "low_temperature",
                "coastal_event",
                "sea_event",
                "forest_fire",
                "avalanches",
                "earthquake",
                "volcano",
                "rain",
                "flooding",
                "tornado",
                "air_quality",
                "dust",
                "tsunami"
            ],
            "properties": {
                "no_warnings": {
                    "$id": "#/properties/events/properties/no_warnings",
                    "type": ["string", "null"]
                },
                "nuclear": {
                    "$id": "#/properties/events/properties/nuclear",
                    "type": ["string", "null"]
                },
                "hurricane": {
                    "$id": "#/properties/events/properties/hurricane",
                    "type": ["string", "null"]
                },
                "wind": {
                    "$id": "#/properties/events/properties/wind",
                    "type": ["string", "null"]
                },
                "snow_ice": {
                    "$id": "#/properties/events/properties/snow_ice",
                    "type": ["string", "null"]
                },
                "thunderstorms": {
                    "$id": "#/properties/events/properties/thunderstorms",
                    "type": ["string", "null"]
                },
                "fog": {
                    "$id": "#/properties/events/properties/fog",
                    "type": ["string", "null"]
                },
                "high_temperature": {
                    "$id": "#/properties/events/properties/high_temperature",
                    "type": ["string", "null"]
                },
                "low_temperature": {
                    "$id": "#/properties/events/properties/low_temperature",
                    "type": ["string", "null"]
                },
                "coastal_event": {
                    "$id": "#/properties/events/properties/coastal_event",
                    "type": ["string", "null"]
                },
                "sea_event": {
                    "$id": "#/properties/events/properties/sea_event",
                    "type": ["string", "null"]
                },
                "forest_fire": {
                    "$id": "#/properties/events/properties/forest_fire",
                    "type": ["string", "null"]
                },
                "avalanches": {
                    "$id": "#/properties/events/properties/avalanches",
                    "type": ["string", "null"]
                },
                "earthquake": {
                    "$id": "#/properties/events/properties/earthquake",
                    "type": ["string", "null"]
                },
                "volcano": {
                    "$id": "#/properties/events/properties/volcano",
                    "type": ["string", "null"]
                },
                "rain": {
                    "$id": "#/properties/events/properties/rain",
                    "type": ["string", "null"]
                },
                "flooding": {
                    "$id": "#/properties/events/properties/flooding",
                    "type": ["string", "null"]
                },
                "tornado": {
                    "$id": "#/properties/events/properties/tornado",
                    "type": ["string", "null"]
                },
                "air_quality": {
                    "$id": "#/properties/events/properties/air_quality",
                    "type": ["string", "null"]
                },
                "dust": {
                    "$id": "#/properties/events/properties/dust",
                    "type": ["string", "null"]
                },
                "tsunami": {
                    "$id": "#/properties/events/properties/tsunami",
                    "type": ["string", "null"]
                }
            },
            "additionalProperties": false
        },
        "messages": {
            "$id": "#/properties/messages",
            "type": "object",
            "required": [
                "yellow",
                "orange",
                "red"
            ],
            "properties": {
                "yellow": {
                    "$id": "#/properties/messages/properties/yellow",
                    "type": "object",
                    "required": [
                      "event",
                      "generic",
                      "color"
                  ],
                  "properties": {
                      "event": {
                          "$id": "#/properties/messages/properties/yellow/properties/event",
                          "type": ["string", "null"]
                      },
                      "generic": {
                          "$id": "#/properties/messages/properties/yellow/properties/generic",
                          "type": ["string", "null"]
                      },
                      "color": {
                          "$id": "#/properties/messages/properties/yellow/properties/color",
                          "type": ["string", "null"]
                      }
                    },
                    "additionalProperties": false
                },
                "orange": {
                    "$id": "#/properties/messages/properties/orange",
                    "type": "object",
                    "required": [
                      "event",
                      "generic",
                      "color"
                  ],
                  "properties": {
                      "event": {
                          "$id": "#/properties/messages/properties/orange/properties/event",
                          "type": ["string", "null"]
                      },
                      "generic": {
                          "$id": "#/properties/messages/properties/orange/properties/generic",
                          "type": ["string", "null"]
                      },
                      "color": {
                          "$id": "#/properties/messages/properties/orange/properties/color",
                          "type": ["string", "null"]
                      }
                    },
                    "additionalProperties": false
                },
                "red": {
                    "$id": "#/properties/messages/properties/red",
                    "type": "object",
                    "required": [
                      "event",
                      "generic",
                      "color"
                  ],
                  "properties": {
                      "event": {
                          "$id": "#/properties/messages/properties/red/properties/event",
                          "type": ["string", "null"]
                      },
                      "generic": {
                          "$id": "#/properties/messages/properties/red/properties/generic",
                          "type": ["string", "null"]
                      },
                      "color": {
                          "$id": "#/properties/messages/properties/red/properties/color",
                          "type": ["string", "null"]
                      }
                    },
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        }
    },
    "additionalProperties": false
}

=== MrBartusek/MeteoalarmCard/src/localize/languages/de.json
{
  "$schema": "../schema/schema.json",
  "common": {
    "name": "Meteoalarm-Karte",
    "description": "Die Meteoalarm-Karte warnt dich vor bevorstehenden Wetterereignissen.",
    "expected": "Erwartet",
    "unavailable": {
      "long": "Integration nicht verfügbar",
      "short": "Nicht verfügbar"
    }
  },
  "error": {
    "missing_entity": "Die angegebene Entität ist nicht vorhanden!",
    "invalid_integration": "Diese Integration ist nicht gültig!",
    "invalid_scaling_mode": null,
    "entity_invalid": {
      "single": "Ausgewählte Integration und Entität passen nicht zusammen.",
      "multiple": "Ausgewählte Integration passt nicht zu Entitäten: {entity}."
    }
  },
  "editor": {
    "entity": "Entität",
    "entities": null,
    "integration": "Integration",
    "required": "Erforderlich",
    "recommended": "Empfohlen",
    "override_headline": "Von der Integration bereitgestellte Überschrift überschreiben",
    "hide_when_no_warning": "Ausblenden, wenn es keine Warnungen gibt",
    "hide_caption": "Beschriftung ausblenden",
    "disable_swiper": "Alarm-Swiper deaktiveren",
    "description": {
      "start": "Ausgewählte Integration erzeugt mehrere Entitäten.",
      "current_expected": "Die erste mit aktuellen, die zweite mit zukünftigen Meldungen.",
      "slots": "Die exakte Anzahl wird durch die Konfiguration bestimmt.",
      "separate_events": "Jeder Ereignistyp erhält eine eigene Entität.",
      "warning_watch_statement_advisory": null,
      "end": "Um keine Warnhinweise zu verpassen, sollten alle ausgewählt werden."
    },
    "error": {
      "expected_entity": "Die erwartete Warnungs-Entität wurde nicht bereitgestellt. Zukünftige Ereignisse werden nicht angezeigt.",
      "too_many_entities": "Es wurden mehr Entitäten als erwartet erzeugt. Erwarten wurde(n) {expected_entities_count}, vorhanden sind {selected_entities_count}.",
      "duplicate": "Doppelte Entitäten in Liste gefunden"
    },
    "scaling_mode": null,
    "scaling_mode_options": {
      "disabled": null,
      "headline": null,
      "scale": null,
      "headline_and_scale": null
    }
  },
  "events": {
    "no_warnings": "Keine Warnungen",
    "nuclear": "Nuklear",
    "tornado": "Tornado",
    "hurricane": "Orkan/Hurrikan",
    "wind": "Wind",
    "earthquake": "Erdbeben",
    "volcano": "Vulkanaktivität",
    "snow_ice": "Schnee/Eis",
    "fog": "Nebel",
    "high_temperature": "Hohe Temperatur",
    "low_temperature": "Niedrige Temperatur",
    "coastal_event": "Küstenereignis",
    "tsunami": "Tsunami",
    "sea_event": "Meeresereignis",
    "forest_fire": "Waldbrand",
    "avalanches": "Lawinen",
    "thunderstorms": "Gewitter",
    "rain": "Regen",
    "flooding": "Hochwasser/Flut",
    "air_quality": "Luftqualität",
    "dust": "Staub"
  },
  "messages": {
    "yellow": {
      "event": "Gelbe Warnung: {event}",
      "generic": "Gelbe Warnung",
      "color": "Gelb"
    },
    "orange": {
      "event": "Orange Warnung: {event}",
      "generic": "Orange Warnung",
      "color": "Orange"
    },
    "red": {
      "event": "Rote Warnung: {event}",
      "generic": "Rote Warnung",
      "color": "Rot"
    }
  }
}

=== MrBartusek/MeteoalarmCard/src/localize/languages/sr-Latn.json
{
  "$schema": "../schema/schema.json",
  "common": {
    "name": "Meteoalarm Card",
    "description": "Meteoalarm kartica vas upozorava na trenutne vremenske događaje.",
    "expected": "Očekivano",
    "unavailable": {
      "long": "Integracija nije dostupna",
      "short": "Nedostupno"
    }
  },
  "error": {
    "missing_entity": "Potrebno je navesti entitete!",
    "invalid_integration": "Ova integracija nije važeća!",
    "invalid_scaling_mode": "Ovaj režim skaliranja nije važeći!",
    "entity_invalid": {
      "single": "Izabrana integracija ne odgovara izabranom entitetu.",
      "multiple": "Izabrana integracija ne odgovara izabranim entitetima: {entity}."
    }
  },
  "editor": {
    "entity": "Entitet",
    "entities": "Entiteti",
    "integration": "Integracija",
    "required": "Obavezno",
    "recommended": "Preporučeno",
    "override_headline": "Zameni naslov koji daje integracija",
    "hide_when_no_warning": "Sakrij kada nema upozorenja",
    "hide_caption": "Sakrij natpis",
    "disable_swiper": "Onemogući klizač upozorenja",
    "description": {
      "start": "Izabrana integracija kreira više entiteta.",
      "current_expected": "Prvi sa trenutnim događajima i drugi sa budućim.",
      "slots": "Tačan broj kreiranih entiteta određuje konfiguracija.",
      "separate_events": "Svaka vrsta događaja ima poseban entitet.",
      "warning_watch_statement_advisory": "Postoje 4 entiteta: upozorenja, nadzori, saopštenja i saveti.",
      "end": "Dodajte sve da biste bili sigurni da nećete propustiti nijedno upozorenje."
    },
    "error": {
      "expected_entity": "Očekivani entitet upozorenja nije obezbeđen. Budući događaj neće biti prikazan.",
      "too_many_entities": "Obezbeđeno je više entiteta nego što je očekivano. Očekivano {expected_entities_count}, dobijeno {selected_entities_count}.",
      "duplicate": "Pronađeni duplikati u listi entiteta."
    },
    "scaling_mode": "Režim skaliranja",
    "scaling_mode_options": {
      "disabled": "Onemogućeno",
      "headline": "Samo naslov",
      "scale": "Samo skala",
      "headline_and_scale": "Naslov i skala"
    }
  },
  "events": {
    "no_warnings": "Nema upozorenja",
    "nuclear": "nuklearni akcedent",
    "tornado": "tornado",
    "hurricane": "uragan",
    "wind": "vetar",
    "earthquake": "zemljotres",
    "volcano": "vulkan",
    "snow_ice": "sneg/led",
    "fog": "magla",
    "high_temperature": "visoka temperatura",
    "low_temperature": "niska temperatura",
    "coastal_event": "obalni događaj",
    "tsunami": "tsunami",
    "sea_event": "nepogode na moru",
    "forest_fire": "šumski požar",
    "avalanches": "lavine",
    "thunderstorms": "grmljavinske oluje",
    "rain": "kiša",
    "flooding": "poplave",
    "air_quality": "kvalitet vazduha",
    "dust": "prašina"
  },
  "messages": {
    "yellow": {
      "event": "Žuto upozorenje za {event}",
      "generic": "Žuto upozorenje",
      "color": "Žuto"
    },
    "orange": {
      "event": "Narandžasto upozorenje za {event}",
      "generic": "Narandžasto upozorenje",
      "color": "Narandžasto"
    },
    "red": {
      "event": "Crveno upozorenje za {event}",
      "generic": "Crveno upozorenje",
      "color": "Crveno"
    }
  }
}

=== MrBartusek/MeteoalarmCard/src/localize/languages/pt.json
{
  "$schema": "../schema/schema.json",
  "common": {
    "name": "Cartão Meteoalarm",
    "description": "O cartão Meteoalarm adverte sobre eventos meteorológicos actuais.",
    "expected": "Esperado",
    "unavailable": {
      "long": "A integração não está disponível",
      "short": "Indisponível"
    }
  },
  "error": {
    "missing_entity": "É necessário especificar a entidade!",
    "invalid_integration": "A integração não é válida!",
    "invalid_scaling_mode": null,
    "entity_invalid": {
      "single": "A integração seleccionada não conincide com a entidade seleccionada.",
      "multiple": "A integração seleccionada não conincide com as entidades seleccionadas: {entity}."
    }
  },
  "editor": {
    "entity": "Entidade",
    "entities": null,
    "integration": "Integração",
    "required": "Necessário",
    "recommended": "Recomendado",
    "override_headline": "Modificar cabeçalho",
    "hide_when_no_warning": "Ocultar quando não há avisos",
    "hide_caption": "Ocultar título",
    "disable_swiper": "Desactivar o deslizador de alertas",
    "description": {
      "start": "A integração seleccionada cria múltiplas entidades.",
      "current_expected": "O primeiro com eventos actuais e o segundo com eventos futuros.",
      "slots": "A quantidade exacta criada é determinada pela sua configuracão.",
      "separate_events": "Cada tipo de evento tem uma entidade separada.",
      "warning_watch_statement_advisory": null,
      "end": "Devem ser agregados para não serem perdidos alertas."
    },
    "error": {
      "expected_entity": "Não foi especificada entidade de avisos esperada. Não se irão mostrar eventos futuros.",
      "too_many_entities": "Foram especificadas mais entidades do que esperado. Esperavam-se {expected_entities_count} entidades, mas foram especificadas {selected_entities_count} entidades.",
      "duplicate": "Encontrados duplicados na lista de entidades."
    },
    "scaling_mode": null,
    "scaling_mode_options": {
      "disabled": null,
      "headline": null,
      "scale": null,
      "headline_and_scale": null
    }
  },
  "events": {
    "no_warnings": "Sem avisos",
    "nuclear": "evento nuclear",
    "tornado": "tornado",
    "hurricane": "furacão",
    "wind": "vento",
    "earthquake": "terremoto",
    "volcano": "vulcão",
    "snow_ice": "neve/gelo",
    "fog": "nevoeiro",
    "high_temperature": "alta temperatura",
    "low_temperature": "baixa temperatura",
    "coastal_event": "fenómeno costeiro",
    "tsunami": "tsunami",
    "sea_event": "evento marinho",
    "forest_fire": "incêndio forestal",
    "avalanches": "avalanches",
    "thunderstorms": "trovoadas",
    "rain": "chuva",
    "flooding": "inundação",
    "air_quality": "qualidade do ar",
    "dust": "pó"
  },
  "messages": {
    "yellow": {
      "event": "Alerta amarelo por {event}",
      "generic": "Alerta amarelo",
      "color": "Amarelo"
    },
    "orange": {
      "event": "Alerta laranja por {event}",
      "generic": "Alerta laranja",
      "color": "Laranja"
    },
    "red": {
      "event": "Alerta vermelho por {event}",
      "generic": "Alerta vermelho",
      "color": "Vermelho"
    }
  }
}
